# Generated by Django 3.1.7 on 2021-04-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210403_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('SOMETHING_ELSE', 'something else')], default='MALE', max_length=14, verbose_name='gender'),
        ),
    ]
