# Generated by Django 3.1.7 on 2021-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210403_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registered'),
        ),
    ]
