text="""[{name: 'John', lastname: 'Doe', age: 24, gender: 'Male', is_staff=false, is_superuser=False, is_active=True}, {name: 'Albert', lastname: 'Einstein', age: 124, gender: 'Male', is_staff=false, is_superuser=False, is_active=True}, {name: 'Feen', lastname: 'Fargoos', age: 45, gender: 'Male', is_staff=false, is_superuser=False, is_active=True}, {name: 'Lili', lastname: 'Batonchek', age: 24, gender: 'Female, is_staff=false, is_superuser=False, is_active=True'}, {name: 'Karen', lastname: 'Lawson', age:67, gender: 'Female', is_staff=false, is_superuser=False, is_active=True}, {name: 'Marshal', lastname: 'Batonchek', age: 24, gender: 'Male', is_staff=false, is_superuser=False, is_active=True}, {name: 'Ted', lastname: 'Mosbey', age:67, gender: 'Male', is_staff=false, is_superuser=False, is_active=True}, {name: 'Aob', lastname: 'Aoe', age: 24, gender: 'Male', is_staff=false, is_superuser=False, is_active=True}, {name: 'Bob', lastname: 'Binstein', age: 124, gender: 'Male', is_staff=false, is_superuser=False, is_active=True}, {name: 'Cob', lastname: 'Cargoos', age: 45, gender: 'Male', is_staff=false, is_superuser=False, is_active=True}, {name: 'Dob', lastname: 'Datonchek', age: 24, gender: 'Female', is_staff=false, is_superuser=False, is_active=True}, {name: 'Eob', lastname: 'Eawson', age:67, gender: 'Female, is_staff=false, is_superuser=False, is_active=True'}, {name: 'Fob', lastname: 'Fatonchek', age: 24, gender: 'Male', is_staff=false, is_superuser=False, is_active=True'}, {name: 'Gob', lastname: 'Gosbey', age:67, gender: 'Male', is_staff=false, is_superuser=False, is_active=True'}, {name: 'Aan', lastname: 'Soe', age: 24, gender: 'Male', is_staff=false, is_superuser=False, is_active=True'}, {name: 'Can', lastname: 'Sinstein', age: 124, gender: 'Male', is_staff=false, is_superuser=False, is_active=True'}, {name: 'Dan', lastname: 'Sargoos', age: 45, gender: 'Male', is_staff=false, is_superuser=False, is_active=True'}, {name: 'Ean', lastname: 'Satonchek', age: 24, gender: 'Female, is_staff=false, is_superuser=False, is_active=True'}, {name: 'Fan', lastname: 'Sawson', age:67, gender: 'Female, is_staff=false, is_superuser=False, is_active=True'}, {name: 'Gan', lastname: 'Satonchek', age: 24, gender: 'Male', is_staff=false, is_superuser=False, is_active=True'}, {name: 'Han', lastname: 'Sosbey', age:67, gender: 'Male', is_staff=false, is_superuser=False, is_active=True}]"""
text = text.replace("{", "(")
text = text.replace("}", ")")
text = text.replace("name=", "first_name=")
text = text.replace("lastname", "last_name")
text = text.replace("Female", "female")
text = text.replace("Male", "male")
text = text.replace(") ", "),")

print (text)